### ISSUE TITLE
Disable background gesture when modal is showing.

### ISSUE THREAD

**Issue by manoj2166** [raynor85/react-native-modal-wrapper#10] opened 2017-11-23 12:54 UTC
I am displaying a full page modal to show a list of snooze timer options to the user - 1 minute, 1 hour, 1 day etc. as buttons in a grid. After removing "`onRequestClose`" from the props, I am able to disable all gesture interactions that the user might do with the background, since in the background I am showing a list of swipe-able list items.  However, on iOS, I am still able to swipe out my navigation drawer menu from the left corner of the screen, even though I am able to disable background button clicks and swipes (on the mentioned list). How can I disable this gesture to make the background  non-interactive ?

**Comment by raynor85** [comment] 2017-11-23 17:08
Can you please add your code and a screenshot of what happens? Even better, it would be great to add an animated gif for these kind of UI problems. I suggest to give GIPHY Capture a try: it allows you to create simple animated gif of your simulator interactions.

**Comment by manoj2166** [comment] 2017-11-24 11:24
Sure,
Thanking you for the reply.
I am sending you GIF link so you can see when I am swiping left to right on open modal my drawer menu open/close in the background.
http://gph.is/2jiCrCk

**Comment by raynor85** [comment] 2017-11-24 20:23
That is weird, as the modal should come with an overlay that prevents you from interacting with the background. Try to set showOverlay={true} (default value for it is still true, but maybe in your implementation you are setting it to false).
Can you also paste the code of the ModalWrapper as well? That would be very helpful.

**Comment by raynor85** [comment] 2017-11-25 01:47
Tip: if the modal has the prop isNative={false}, the screen underneath still accept the panHandler, so you can actually interact with it and navigate back if you drag from the left edge of the screen (for example). It is probably the case. If you want to fix it, try to disable the panHandlers when you open the modal and re enable them when you close it, or even better, don't set the prop isNative={false} (the default is isNative={true}, so you don't need to specify it)

**Comment by manoj2166** [comment] 2017-11-28 04:29
Thanks for the reply.
Here is the code that I am using for the ModalWrapper. 

```
<ModalWrapper
style={styles.container}
containerStyle={{flexDirection: 'row', backgroundColor: 'black', opacity: .8}}
position="right"
visible={this.props.isVisible}>
<ScrollView>
    ....
</ScrollView>
</ModalWrapper>

```
Also, I forgot to mention before, this problem of the background interaction is only on iOS, I am not experiencing it on Android. **showOverlay** is not being set by me explicitly, so its value is true only (by default).

**Comment by raynor85** [comment] 2017-11-28 20:11
I can't reproduce the issue with your code. With that configuration on iOS I can't navigate back and forth if the modal is open. It would be possible only if the prop isNative is being set to false. Be sure it is not the case, and if you can't make it work, try to use the Native Modal component. Replicating the issue using a tool like https://snack.expo.io/ would be good too.

**Comment by raynor85** [comment] 2017-11-28 20:19
FYI: you can't experience it on Android because from my knowledge only iOS has a pan handler by default that allows you to navigate back and forth through your app (at least this is happening with startSingleScreenApp of the amazing react-native-navigation plugin by wix). If you don't like this swiping behaviour (described here http://osxdaily.com/2013/11/27/use-swipe-gesture-to-go-back-ios/), check out in the documentation of the navigation plugin you are using to disable it.

**Comment by raynor85** [comment] 2017-12-10 00:46
Closed due to lack of informations needed to replicate the issue.

**Closed as completed by raynor85** 2017-12-10 00:46 UTC
